[2025-03-13T21:22:06.950+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-13T21:22:06.984+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: open_weather_etl.test manual__2025-03-13T21:22:03.565808+00:00 [queued]>
[2025-03-13T21:22:07.256+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: open_weather_etl.test manual__2025-03-13T21:22:03.565808+00:00 [queued]>
[2025-03-13T21:22:07.257+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-13T21:22:07.262+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): test> on 2025-03-13 21:22:03.565808+00:00
[2025-03-13T21:22:07.268+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=126) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-13T21:22:07.270+0000] {standard_task_runner.py:72} INFO - Started process 127 to run task
[2025-03-13T21:22:07.272+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'open_weather_etl', 'test', 'manual__2025-03-13T21:22:03.565808+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp2v80khyj']
[2025-03-13T21:22:07.280+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask test
[2025-03-13T21:22:07.325+0000] {task_command.py:467} INFO - Running <TaskInstance: open_weather_etl.test manual__2025-03-13T21:22:03.565808+00:00 [running]> on host 7499a3ac39c6
[2025-03-13T21:22:07.364+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='open_weather_etl' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T21:22:03.565808+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-13T21:22:03.565808+00:00'
[2025-03-13T21:22:07.364+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-13T21:22:07.381+0000] {logging_mixin.py:190} INFO - Running test task...
[2025-03-13T21:22:07.382+0000] {logging_mixin.py:190} INFO - Just random test to create
[2025-03-13T21:22:07.382+0000] {logging_mixin.py:190} INFO - Test task complete.
[2025-03-13T21:22:07.388+0000] {python.py:240} INFO - Done. Returned value was: Test completed successfully!
[2025-03-13T21:22:07.396+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-13T21:22:07.396+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=open_weather_etl, task_id=test, run_id=manual__2025-03-13T21:22:03.565808+00:00, execution_date=20250313T212203, start_date=20250313T212206, end_date=20250313T212207
[2025-03-13T21:22:07.412+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-13T21:22:07.420+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T21:22:07.420+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
